# Supabase Project Configuration
project_id = "sgi-ati"

[functions.login-cpf]
enabled = true
verify_jwt = false

[functions.invite-user]
enabled = true
verify_jwt = true

[functions.delete-user]
enabled = true
verify_jwt = true

[functions.send-feedback]
enabled = true
verify_jwt = false
